### ISSUE TITLE
Game crashed when attacked by cobra

### ISSUE THREAD

**Issue by inkdear** [Xenoform55/Worlds-Retold#7]
Crash report:

EDIT: I reloaded the world, got attacked by the same cobra, and got the same crash. 

SECOND EDIT: I now have strong reason to believe this is Respawnable Pets' newest version's fault, not Worlds Retold.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3 (1).jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0 (1).jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  MuonPlugin (muon-0.2-1.12.jar)
  McLib core mod (mclib-1.0.3-1.12.2 (1).jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2 (1).jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/26/19 1:10 PM
Description: Ticking entity

java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138)
	at net.minecraft.entity.Entity.serializeNBT(Entity.java:3132)
	at moriyashiine.respawnablepets.Util.getOwner(Util.java:13)
	at moriyashiine.respawnablepets.ModEventHandler.livingDamage(ModEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_728_ModEventHandler_livingDamage_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:609)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at xenoscape.worldsretold.defaultmod.basic.EntitySurfaceMonster.func_70652_k(EntitySurfaceMonster.java:89)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra.func_70652_k(EntityCobra.java:183)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra$AICobraAttack.checkAndPerformAttack(EntityCobra.java:411)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra$AICobraAttack.func_75246_d(EntityCobra.java:402)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at xenoscape.worldsretold.defaultmod.basic.EntitySurfaceMonster.func_70636_d(EntitySurfaceMonster.java:38)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at xenoscape.worldsretold.defaultmod.basic.EntitySurfaceMonster.func_70071_h_(EntitySurfaceMonster.java:42)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra.func_70071_h_(EntityCobra.java:100)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138)
	at net.minecraft.entity.Entity.serializeNBT(Entity.java:3132)
	at moriyashiine.respawnablepets.Util.getOwner(Util.java:13)
	at moriyashiine.respawnablepets.ModEventHandler.livingDamage(ModEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_728_ModEventHandler_livingDamage_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:609)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at xenoscape.worldsretold.defaultmod.basic.EntitySurfaceMonster.func_70652_k(EntitySurfaceMonster.java:89)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra.func_70652_k(EntityCobra.java:183)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra$AICobraAttack.checkAndPerformAttack(EntityCobra.java:411)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra$AICobraAttack.func_75246_d(EntityCobra.java:402)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at xenoscape.worldsretold.defaultmod.basic.EntitySurfaceMonster.func_70636_d(EntitySurfaceMonster.java:38)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at xenoscape.worldsretold.defaultmod.basic.EntitySurfaceMonster.func_70071_h_(EntitySurfaceMonster.java:42)
	at xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra.func_70071_h_(EntityCobra.java:100)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: worldsretold:cobra (xenoscape.worldsretold.heatwave.entity.neutral.cobra.EntityCobra)
	Entity ID: 26495
	Entity Name: Cobra
	Entity's Exact location: 185.48, 68.00, 520.52
	Entity's Block location: World: (185,68,520), Chunk: (at 9,4,8 in 11,32; contains blocks 176,0,512 to 191,255,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: doodley doo
	All players: 1 total; [EntityPlayerMP['Inkdeer'/521, l='doodley doo', x=183.74, y=68.00, z=521.17]]
	Chunk stats: ServerChunkCache: 967 Drop: 0
	Level seed: 3688346266851614776
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (111,64,129), Chunk: (at 15,4,1 in 6,8; contains blocks 96,0,128 to 111,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 382152 game time, 25312 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 46389 (now: false), thunder time: 25909 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 763674848 bytes (728 MB) / 1677967360 bytes (1600 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 92 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                 | Version                     | Source                                              | Signature                                |
	|:------ |:---------------------------------- |:--------------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                          | 1.12.2                      | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                                | 9.42                        | minecraft.jar                                       | None                                     |
	| LCHIJA | FML                                | 8.0.99.99                   | forge-1.12.2-14.23.5.2838.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                              | 14.23.5.2838                | forge-1.12.2-14.23.5.2838.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | muon                               | 0.2                         | minecraft.jar                                       | None                                     |
	| LCHIJA | foamfixcore                        | 7.7.4                       | minecraft.jar                                       | None                                     |
	| LCHIJA | randompatches                      | 1.12.2-1.17.2.1             | randompatches-1.12.2-1.17.2.1.jar                   | None                                     |
	| LCHIJA | airhop                             | 1.1                         | AirHop-v1.1-1.12.2.jar                              | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCHIJA | applecore                          | 3.2.0                       | AppleCore-mc1.12.2-3.2.0 (1).jar                    | None                                     |
	| LCHIJA | charcoal_pit                       | 1.20                        | CharcoalPit-[1.12]-1.20.jar                         | None                                     |
	| LCHIJA | jei                                | 4.15.0.268                  | jei_1.12.2-4.15.0.268.jar                           | None                                     |
	| LCHIJA | appleskin                          | 1.0.9                       | AppleSkin-mc1.12-1.0.9.jar                          | None                                     |
	| LCHIJA | attributefix                       | 1.0.4                       | AttributeFix-1.12.2-1.0.4 (1).jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | baubles                            | 1.5.2                       | Baubles-1.12-1.5.2.jar                              | None                                     |
	| LCHIJA | bettercombatmod                    | 1.5.6                       | BetterCombat-1.12.2-1.5.6.jar                       | None                                     |
	| LCHIJA | biomesoplenty                      | 7.0.1.2439                  | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar       | None                                     |
	| LCHIJA | byg                                | 1.6.8b2                     | BiomesYouGo1.6.8.jar                                | None                                     |
	| LCHIJA | bookshelf                          | 2.3.585                     | Bookshelf-1.12.2-2.3.585.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | cursedlib                          | 1.0.0                       | FlameLib-1.12.2-0.0.7.jar                           | None                                     |
	| LCHIJA | bountifulbaubles                   | 0.0.1                       | Bountiful+Baubles-1.12.2-0.0.8 (1).jar              | None                                     |
	| LCHIJA | cloudboots                         | 1.4.1                       | CloudBoots-1.12.2-1.4.1.jar                         | None                                     |
	| LCHIJA | clumps                             | 3.1.2                       | Clumps-3.1.2.jar                                    | None                                     |
	| LCHIJA | combatrefined                      | 1.4.1                       | combatrefined-1.4.1.jar                             | None                                     |
	| LCHIJA | complexcrops                       | v4.2.0                      | Complex+Crops+1.12.2-4.2.0.jar                      | None                                     |
	| LCHIJA | crafttweaker                       | 4.1.19                      | CraftTweaker2-1.12-4.1.19.jar                       | None                                     |
	| LCHIJA | ctgui                              | 1.0.0                       | CraftTweaker2-1.12-4.1.19.jar                       | None                                     |
	| LCHIJA | crafttweakerjei                    | 2.0.3                       | CraftTweaker2-1.12-4.1.19.jar                       | None                                     |
	| LCHIJA | crude_start                        | 1.0.0                       | CrudeStart-1.0.jar                                  | None                                     |
	| LCHIJA | cucumber                           | 1.1.3                       | Cucumber-1.12.2-1.1.3.jar                           | None                                     |
	| LCHIJA | dungeontactics                     | DT-0.16.5                   | DungeonTactics-1.12.2-0.16.5.jar                    | None                                     |
	| LCHIJA | eerieentities                      | 1.0.7                       | EerieEntities-1.12.2-1.0.7.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | mclib                              | 1.0.3                       | mclib-1.0.3-1.12.2 (1).jar                          | None                                     |
	| LCHIJA | emoticons                          | 0.3                         | emoticons-0.3-1.12.2-dist.jar                       | None                                     |
	| LCHIJA | end_spectre                        | 1.0                         | end_spectre-1.0.jar                                 | None                                     |
	| LCHIJA | endergetic                         | 0.0.1                       | endergetic-0.0.1.jar                                | None                                     |
	| LCHIJA | minerva                            | 1.0.13                      | minerva-library-1.0.13.jar                          | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCHIJA | extraalchemy                       | 0.4.1                       | extraalchemy-0.4.1.jar                              | None                                     |
	| LCHIJA | fastfurnace                        | 1.3.1                       | FastFurnace-1.12.2-1.3.1.jar                        | None                                     |
	| LCHIJA | fastbench                          | 1.7.2                       | FastWorkbench-1.12.2-1.7.2.jar                      | None                                     |
	| LCHIJA | mod_lavacow                        | 1.0.3                       | Fishs_Undead_Rising-1.0.6.jar                       | None                                     |
	| LCHIJA | foamfix                            | 0.10.5-1.12.2               | foamfix-0.10.5-1.12.2 (1).jar                       | None                                     |
	| LCHIJA | foamflower                         | 1.12.2-1.0.0.0-beta1        | foamflower-1.12.2-1.0.0.0-beta1.jar                 | None                                     |
	| LCHIJA | glassjaw                           | MC1.12_ver1.0.1             | GlassJaw-MC1.12_ver1.0.1.jar                        | None                                     |
	| LCHIJA | harvestersnight                    | 1.1.0                       | harvestersnight-1.12.2-1.1.0.jar                    | None                                     |
	| LCHIJA | healthhungertweaks                 | 2.1.1                       | healthhungertweaks-1.12-2.1.1.jar                   | None                                     |
	| LCHIJA | hunterillager                      | 1.2                         | hunterillager-1.12.2-1.2.jar                        | None                                     |
	| LCHIJA | llibrary                           | 1.7.19                      | llibrary-1.7.19-1.12.2 (3).jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                         | 1.8.1                       | iceandfire-1.8.1.jar                                | None                                     |
	| LCHIJA | reborncore                         | 3.16.0.469                  | RebornCore-1.12.2-3.16.0.469-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | justsleep                          | 1.0.0.1                     | JustSleep-1.0.0.1.jar                               | None                                     |
	| LCHIJA | libraryex                          | 1.0.11                      | LibraryEx-1.12.2-1.0.11.jar                         | None                                     |
	| LCHIJA | magma_monsters                     | 0.3.0                       | MagmaMonsters-0.3.0.jar                             | None                                     |
	| LCHIJA | testdummy                          | 1.12                        | MmmMmmMmmMmm-1.12-1.14.jar                          | None                                     |
	| LCHIJA | mowziesmobs                        | 1.5.4                       | mowziesmobs-1.5.4 (1).jar                           | None                                     |
	| LCHIJA | multimob                           | 1.0.5                       | multimob-1.0.5.jar                                  | None                                     |
	| LCHIJA | netherex                           | 2.0.12                      | NetherEx-1.12.2-2.0.12.jar                          | None                                     |
	| LCHIJA | notenoughcats                      | 1.2.1                       | NotEnoughCats-1.12.2-1.2.1.jar                      | None                                     |
	| LCHIJA | noworldgen5you                     | 1.0.6                       | NoWorldgen5You-1.12.2-1.0.6.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | outfox                             | 0.1.3                       | outfox-0.1.3-mc1.12.2.jar                           | None                                     |
	| LCHIJA | parry                              | 1.0                         | parry-1.0-hotfix.jar                                | None                                     |
	| LCHIJA | petbat                             | 1.4.8                       | PetBat-1.12.2.jar                                   | None                                     |
	| LCHIJA | potioncore                         | 1.8_for_1.12.2              | PotionCore-1.8_for_1.12.2.jar                       | None                                     |
	| LCHIJA | primal                             | 0.6.105                     | PrimalCore-1.12.2-0.6.105.jar                       | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LCHIJA | primitivemobs                      | 1.2.3a                      | primitivemobs-1.2.3a.jar                            | None                                     |
	| LCHIJA | pvj                                | 1.6.3                       | ProjectVibrantJourneys-1.12.2-1.6.3 (1).jar         | None                                     |
	| LCHIJA | randomtweaks                       | 1.12.2-2.7.1.0              | randomtweaks-1.12.2-2.7.1.0.jar                     | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LCHIJA | resourceloader                     | 1.5.3                       | ResourceLoader-MC1.12.1-1.5.3 (1).jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | respawnablepets                    | 1.0.5                       | respawnablepets-1.0.5.jar                           | None                                     |
	| LCHIJA | roughmobs                          | 2.0.0                       | roughmobs2-1.12.2_2.0.15.jar                        | None                                     |
	| LCHIJA | sbmlizarddogo                      | 1.12.2-1.0.0.20190112155428 | SBM-Lizard-Dogo-1.12.2-1.0.0.jar                    | None                                     |
	| LCHIJA | sbmpuntanimal                      | 1.12.2-1.0.0.20190202141056 | SBM-Punt-Animal-1.12.2-1.0.0b20190202141059.jar     | None                                     |
	| LCHIJA | spartanshields                     | 1.5.4                       | SpartanShields-1.12.2-1.5.4.jar                     | None                                     |
	| LCHIJA | spartanweaponry                    | beta 1.3.0                  | SpartanWeaponry-1.12.2-beta-1.3.0.jar               | None                                     |
	| LCHIJA | shinygear                          | 1.5                         | shinygear-1.5.jar                                   | None                                     |
	| LCHIJA | specialai                          | 1.1.0_for_mc1.12.2          | specialai-1.1.0_for_mc1.12.2 (1).jar                | None                                     |
	| LCHIJA | specialmobs                        | 1.0.2_for_mc1.12.2          | specialmobs-1.0.2_for_mc1.12.2.jar                  | None                                     |
	| LCHIJA | strawgolem                         | 1.3                         | strawgolem-1.4.1.jar                                | None                                     |
	| LCHIJA | sm                                 | 1.1                         | Sunglasses+and+more+1.1.jar                         | None                                     |
	| LCHIJA | swampland                          | 2.2                         | Swamp-2.2 (2).jar                                   | None                                     |
	| LCHIJA | shetiphiancore                     | 3.5.9                       | shetiphiancore-1.12.0-3.5.9 (1).jar                 | None                                     |
	| LCHIJA | terraqueous                        | 1.4.17                      | terraqueous-1.12.2-1.4.17b (1).jar                  | None                                     |
	| LCHIJA | themodthatletsyoupunchwooloffsheep | 1.1.0                       | TheModThatLetsYouPunchWoolOffSheep-1.12.2-1.1.0.jar | None                                     |
	| LCHIJA | thesummoner                        | 1.0.1-beta                  | thesummoner-1.0.1.jar                               | None                                     |
	| LCHIJA | trumpetskeleton                    | 1.12-1.0.2.1                | trumpetskeleton-1.12-1.0.2.1.jar                    | None                                     |
	| LCHIJA | vending                            | 1.12.2-3.0.1.2              | vending-1.12.2-3.0.1.2.jar                          | None                                     |
	| LCHIJA | waystones                          | 4.0.72                      | Waystones_1.12.2-4.0.72.jar                         | None                                     |
	| LCHIJA | weirdinggadget                     | 1.0                         | weirdinggadget-1.12.2-2.1.16-universal.jar          | None                                     |
	| LCHIJA | xlfoodmod                          | 1.12.2-1.9.2                | XL-Food-Mod-1.12.2-1.9.2 (1).jar                    | None                                     |
	| LCHIJA | zoocraftdiscoveries                | 1.0                         | Zoocraft+Discoveries+1.12.2-1.3.0 (1).jar           | None                                     |
	| LCHIJA | worldsretold                       | 1.0.5                       | Worlds+Retold-+(v1.0.5)+14.23.5.2784.jar            | None                                     |
	| LCHIJA | gravelores                         | 1.8                         | gravelores-1.8.jar                                  | None                                     |
	| UD     | mclib_core                         | 1.0.3                       | minecraft.jar                                       | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3 (1).jar)
  lumien.resourceloader.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0 (1).jar)
  squeek.applecore.asm.TransformerModuleHandler
Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
MuonPlugin (muon-0.2-1.12.jar)
  gd.izno.mc.muon.MuonClassTransformer
McLib core mod (mclib-1.0.3-1.12.2 (1).jar)
  mchorse.mclib.core.McLibCMClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2 (1).jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.16.0.469
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Inkdeer'/521, l='doodley doo', x=183.74, y=68.00, z=521.17]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Andromander** [comment]
I would suggest reporting this to Respawnable Pets.

**Comment by inkdear** [comment]
Yeah, I just figured that one out and am reporting it to them now. Sorry for the bother.
